# quickDb服务配置
spring:
  profiles:
    active: dev
    include: quickDb
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: quickDb
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    locale: zh_CN
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  pid:
    file: ${server.tomcat.basedir}/${spring.application.name}.pid
  #freemarker
  freemarker:
    #req访问request
    request-context-attribute: req
    #后缀名
    suffix:
    content-type: text/html
    # Content-Type value
    enabled: true
    #是否启用模板缓存
    cache: false
    #模板加载路径 按需配置
    template-loader-path: classpath:/templates/
    #模板编码
    charset: UTF-8
    # setRequestContextAttribute
    settings:
      #数字格式化，无小数点
      number_format: '0.##'
    # 是否允许HttpServletRequest属性覆盖(隐藏)控制器生成的同名模型属性
    allow-request-override: false
    # 是否允许HttpSession属性覆盖(隐藏)控制器生成的同名模型属性
    allow-session-override: false
    # 是否检查模板位置是否存在
    check-template-location: true
    # 设定所有request的属性在merge到模板的时候，是否要都添加到model中.
    expose-request-attributes: false
    # 是否在merge模板的时候，将HttpSession属性都添加到model中
    expose-session-attributes: false
    # 设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
    expose-spring-macro-helpers: true
    # 是否优先从文件系统加载template，以支持热加载，默认为true
    prefer-file-system-access: true
  main:
    allow-bean-definition-overriding: true

# 服务端口号
server:
  port: 9090
  tomcat:
    # 解决上传文件丢失问题
    basedir: ${user.home}/spring-boot/${spring.application.name}/tomcat
  #客户端Http请求、响应的Header的最大限制
  max-http-header-size: 10MB
  #压缩数据传输
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - image/png
      - image/jpeg
      - image/jpg
      - text/html
      - application/javascript
      - text/css
      - application/octet-stream
      - application/json
  servlet:
    # 可以根据具体的应用修改
    context-path: /quickDbApi
